### ISSUE TITLE
Malware

### ISSUE THREAD

**Issue by SubjectULTIMA** [matyalatte/FF7R_text_mod_tools#2]
Google and my antivirus started freaking out when I downloaded this. This is a false positive, right?

**Comment by matyalatte** [comment]
Yes, that is a pyinstaller issue.
There is something I can do. But it will not completely solve the issue.
If you are worried about it, please run [the Python scripts](https://github.com/matyalatte/FF7R_text_mod_tools/tree/main/src) instead of .exe files.

**Comment by SubjectULTIMA** [comment]
So I ended up just using the .exe files but now it's giving me this error

usage: uexp_to_json.exe [-h] [--mode MODE] [--json JSON] [--out_dir OUT_DIR]
                        [--vorbose]
                        uexp
uexp_to_json.exe: error: unrecognized arguments: Text Tools\Resident_TxtRes.uexp
Press any key to continue . . .

**Comment by SubjectULTIMA** [comment]
Nevermind I found the issue.

**Comment by matyalatte** [comment]
I forgot to support whitespaces in file names.
I'll fix the batch files in the next update.

**Comment by matyalatte** [comment]
I've uploaded [the new version](https://github.com/matyalatte/FF7R_text_mod_tools/releases/tag/v1.4.0).
Can you download it and report the result of virus scanning?

**Comment by SubjectULTIMA** [comment]
It still tells me there's a virus

EDIT: Wait only chrome seems to be telling me it is. Malwarebytes and Windows Security don't detect anything

EDIT 2: uhhh nevermind

**Comment by matyalatte** [comment]
I'm glad to hear the situation has improved a bit.
It seems there are still some problems, but there is nothing more I can do.
So, I'll close this issue.
Thank you for the report.
